import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("🚀 Deploying CampaignLedger...\n");

  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "ETH\n");

  // Deploy CampaignLedger
  const CampaignLedgerFactory = await ethers.getContractFactory("CampaignLedger");
  const campaignLedger = await CampaignLedgerFactory.deploy(deployer.address);
  await campaignLedger.waitForDeployment();

  const contractAddress = await campaignLedger.getAddress();
  console.log("✅ CampaignLedger deployed to:", contractAddress);

  // Get network info
  const network = await ethers.provider.getNetwork();
  const chainId = Number(network.chainId);
  console.log("Chain ID:", chainId);

  // Get block 0 hash for fingerprinting
  const genesisBlock = await ethers.provider.getBlock(0);
  const genesisHash = genesisBlock?.hash || "0x";
  console.log("Genesis hash:", genesisHash);

  // Read ABI from artifacts
  const artifactPath = path.join(__dirname, "../artifacts/contracts/CampaignLedger.sol/CampaignLedger.json");
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));

  // Export to web package
  const webContractsDir = path.join(__dirname, "../../web/src/lib");

  // Ensure directory exists
  if (!fs.existsSync(webContractsDir)) {
    fs.mkdirSync(webContractsDir, { recursive: true });
  }

  // Generate contracts.ts file
  const contractsFile = `// Auto-generated by deploy script - DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}

export const CAMPAIGN_LEDGER_ADDRESS = "${contractAddress}" as const;

export const CHAIN_ID = ${chainId} as const;

export const GENESIS_HASH = "${genesisHash}" as const;

export const CAMPAIGN_LEDGER_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  const outputPath = path.join(webContractsDir, "contracts.ts");
  fs.writeFileSync(outputPath, contractsFile);
  console.log("\n✅ Contract info exported to:", outputPath);

  // Also create a JSON file for easy reading
  const deploymentInfo = {
    contractAddress,
    chainId,
    genesisHash,
    deployedAt: new Date().toISOString(),
    deployerAddress: deployer.address,
  };

  const jsonPath = path.join(webContractsDir, "deployment.json");
  fs.writeFileSync(jsonPath, JSON.stringify(deploymentInfo, null, 2));
  console.log("✅ Deployment info exported to:", jsonPath);

  console.log("\n🎉 Deployment complete!");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Deployment failed:", error);
    process.exit(1);
  });
